{pkgs}: {
  deps = [
    pkgs.jdk
    pkgs.openjdk17
    pkgs.jdk17
    pkgs.android-tools
    pkgs.gradle
    pkgs.wineWowPackages.stable
    pkgs.xorg.xorgserver
    pkgs.libgbm
    pkgs.systemd
    pkgs.xorg.libXScrnSaver
    pkgs.xorg.libXtst
    pkgs.xorg.libXrender
    pkgs.xorg.libXi
    pkgs.xorg.libxcb
    pkgs.xorg.libXrandr
    pkgs.xorg.libXfixes
    pkgs.xorg.libXext
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.xorg.libX11
    pkgs.libxkbcommon
    pkgs.gdk-pixbuf
    pkgs.cairo
    pkgs.pango
    pkgs.alsa-lib
    pkgs.mesa
    pkgs.libdrm
    pkgs.expat
    pkgs.dbus
    pkgs.cups
    pkgs.at-spi2-atk
    pkgs.atk
    pkgs.nspr
    pkgs.nss
    pkgs.gtk3
    pkgs.glib
  ];
}
