// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ems-warehouse/Dashboard.tsx": () => import("../components/mockups/ems-warehouse/Dashboard.tsx"),
  "./components/mockups/ems-warehouse/Inventory.tsx": () => import("../components/mockups/ems-warehouse/Inventory.tsx"),
  "./components/mockups/ems-warehouse/Login.tsx": () => import("../components/mockups/ems-warehouse/Login.tsx"),
  "./components/mockups/ems-warehouse/PlanDocument.tsx": () => import("../components/mockups/ems-warehouse/PlanDocument.tsx"),
  "./components/mockups/ems-warehouse/SearchAdvanced.tsx": () => import("../components/mockups/ems-warehouse/SearchAdvanced.tsx"),
  "./components/mockups/ems-warehouse/Settings.tsx": () => import("../components/mockups/ems-warehouse/Settings.tsx"),
  "./components/mockups/ems-warehouse/Statistics.tsx": () => import("../components/mockups/ems-warehouse/Statistics.tsx"),
  "./components/mockups/ems-warehouse/Users.tsx": () => import("../components/mockups/ems-warehouse/Users.tsx")
};
